/** Editorial defaults for the A Sỉn design; commerce values remain in products. */
export const ASIN_CONTENT: Record<string, string> = {
  "hero.eyebrow": "ĐẶC SẢN TÂY BẮC",
  "hero.line1": "Tinh hoa",
  "hero.line2": "Tây Bắc",
  "hero.line3": "trong một món quà.",
  "hero.description":
    "Những hương vị được tuyển chọn từ vùng cao, mang theo câu chuyện về con người, văn hóa và vùng đất Tây Bắc.",
  "hero.image": "/images/asin/hero-watercolor.webp",
  "hero.cta": "Khám phá sản phẩm",
  "hero.link": "/san-pham",
  "products.title": "Hương vị\ntừ vùng cao.",
  "products.description": "Đậm đà hương khói bếp, thơm nồng gia vị núi rừng.",
  "story.title": "Nơi hương vị\nbắt đầu từ\nnhững người\nvùng cao.",
  "story.description":
    "A Sỉn lựa chọn những đặc sản được gìn giữ qua nhiều thế hệ, đồng hành cùng bà con vùng cao để mang những hương vị nguyên bản đến gần hơn với bạn.",
  "story.image": "/images/asin/story-village.webp",
  "story.backgroundImage": "/images/asin/story-map-paper.webp",
  "story.portraitImage": "/images/asin/story-portrait.webp",
  "story.meatImage": "/images/asin/story-smoked-meat.webp",
  "story.terracesImage": "/images/asin/story-terraces.webp",
  "story.stat1": "200+",
  "story.stat1Label": "Hộ nông dân đồng hành",
  "story.stat2": "5",
  "story.stat2Label": "Dòng sản phẩm chủ lực",
  "story.stat3": "100%",
  "story.stat3Label": "Truy xuất nguồn gốc",
  "gift.title": "Món quà\ntừ núi rừng.",
  "gift.description":
    "Tinh tế – Sang trọng – Đậm chất Tây Bắc. Trao tặng gia đình, bạn bè và đối tác một món quà mang dấu ấn riêng.",
  "gift.image": "/images/asin/gift-reference.webp",
  "gift.secondaryImage": "/images/asin/gift.webp",
  "gift.cta": "Khám phá hộp quà",
  "gift.link": "/thiet-ke",
  "journey.image": "/images/asin/journey-panorama.webp",
  "shop.title": "Hương vị từ vùng cao.\nGửi trọn trong từng món quà.",
  "shop.intro":
    "Khám phá những đặc sản mang hương khói bếp và gia vị núi rừng Tây Bắc.",
  "shop.image": "/images/asin/hero-watercolor.webp",
  "about.heroImage": "/images/asin/story.webp",
  "about.storyImage": "/images/asin/story.webp",
  "about.title": "Từ con người vùng cao.\nĐến một món quà chân thành.",
  "about.heading": "Nơi hương vị bắt đầu.",
  "values.1.title": "Nguồn gốc rõ ràng",
  "values.1.text": "Tìm hiểu câu chuyện sản phẩm",
  "values.2.title": "Đặc sản tuyển chọn",
  "values.2.text": "Hương vị đặc trưng Tây Bắc",
  "values.3.title": "Bao bì chỉn chu",
  "values.3.text": "Phù hợp làm quà tặng",
  "values.4.title": "Trải nghiệm 3D",
  "values.4.text": "Xem sản phẩm nhiều góc độ",
};
export const SIGNATURE_PRODUCTS = [
  {
    id: "trau-gac-bep-tay-bac",
    name: "Thịt trâu gác bếp",
    image: "/images/products/buffalo.webp",
    type: "ĐẶC SẢN GÁC BẾP",
  },
  {
    id: "thit-lon-gac-bep",
    name: "Thịt lợn gác bếp",
    image: "/images/products/pork.webp",
    type: "ĐẶC SẢN GÁC BẾP",
  },
  {
    id: "lap-xuong-gac-bep",
    name: "Lạp xưởng gác bếp",
    image: "/images/products/sausage.webp",
    type: "ĐẶC SẢN GÁC BẾP",
  },
  {
    id: "cham-cheo",
    name: "Chẩm chéo",
    image: "/images/products/cham-cheo.webp",
    type: "GIA VỊ NÚI RỪNG",
  },
  {
    id: "thit-trau-xe",
    name: "Thịt trâu xé",
    image: "/images/products/shredded-buffalo.webp",
    type: "HƯƠNG VỊ TÂY BẮC",
  },
  {
    id: "thit-lon-xe",
    name: "Thịt lợn xé",
    image: "/images/products/shredded-pork.webp",
    type: "HƯƠNG VỊ TÂY BẮC",
  },
];
export const PORK_MODEL = "/3Dfile/thit_lon_say_tay_bac.glb";
